"""Numerical checks from the design review of 2026-07-26.

Three checks, all exact integer/rational arithmetic (no floats):

  1. H+_II (attractor regime, v_p(delta)=m>=1, orbit in Zp^2): forward
     precision-lattice divisor exponents are (0, t*m) — pure gain, no loss —
     and backward exponents are (-(T-t)*m, 0) — pure loss. Hence the
     smoother is vacuous there (F ∩ B = F).
  2. H_III (horseshoe) at a fixed point: forward exponents (-t, t) — genuine
     loss of t digits in the unstable direction — backward mirrored.
  3. H_III smoother: the intersected lattice has exponents
     (min(t, T-t), T - min(t, T-t)): worst-direction precision is a bounded
     tent instead of linear loss.

Henon form used: f(x,y) = (y, y^2 + c - delta*x),
J = [[0,1],[-delta,2y]], det J = delta.
"""

from fractions import Fraction as F
from math import gcd

INF = 10**9


def vp(n, p):
    if n == 0:
        return INF
    if isinstance(n, F):
        return vp(n.numerator, p) - vp(n.denominator, p)
    v, n = 0, abs(n)
    while n % p == 0:
        n //= p
        v += 1
    return v


def snf_vals(M, p):
    """Valuations (d1, d2), d1 <= d2, of elementary divisors of a 2x2
    full-rank matrix with entries in Q (viewed over Z_p)."""
    a, b, c, d = M[0][0], M[0][1], M[1][0], M[1][1]
    d1 = min(vp(x, p) for x in (a, b, c, d))
    return d1, vp(a * d - b * c, p) - d1


def matmul(A, B):
    return [[sum(A[i][k] * B[k][j] for k in range(2)) for j in range(2)]
            for i in range(2)]


def inv(M):
    a, b, c, d = M[0][0], M[0][1], M[1][0], M[1][1]
    det = a * d - b * c
    return [[d / det, -b / det], [-c / det, a / det]]


def transpose(M):
    return [[M[0][0], M[1][0]], [M[0][1], M[1][1]]]


def hnf_cols(cols):
    """Column-style HNF basis of the lattice generated by integer 2-vectors."""
    cols = [list(c) for c in cols if c != [0, 0]]
    while True:
        nz = [c for c in cols if c[0] != 0]
        if len(nz) <= 1:
            break
        nz.sort(key=lambda c: abs(c[0]))
        piv = nz[0]
        for c in cols:
            if c is not piv and c[0] != 0:
                q = c[0] // piv[0]
                c[0] -= q * piv[0]
                c[1] -= q * piv[1]
    first = [c for c in cols if c[0] != 0]
    g2 = 0
    for c in cols:
        if c[0] == 0:
            g2 = gcd(g2, c[1])
    assert first and g2, "lattice not full rank"
    return [[first[0][0], 0], [first[0][1], g2]]


def intersect(A, B):
    """Intersection of the lattices A*Z^2 and B*Z^2 via duals:
    (L1 ∩ L2)* = L1* + L2*, dual of A*Z^2 being A^{-T}*Z^2."""
    Ad, Bd = transpose(inv(A)), transpose(inv(B))
    cols = [[Ad[0][0], Ad[1][0]], [Ad[0][1], Ad[1][1]],
            [Bd[0][0], Bd[1][0]], [Bd[0][1], Bd[1][1]]]
    D = 1
    for c in cols:
        for x in c:
            D = D * x.denominator // gcd(D, x.denominator)
    H = hnf_cols([[int(x * D) for x in c] for c in cols])
    Hq = [[F(H[i][j], D) for j in range(2)] for i in range(2)]
    return transpose(inv(Hq))


def jac(x, y, delta):
    return [[F(0), F(1)], [F(-delta), F(2 * y)]]


def jac_inv(x, y, delta):
    d = F(delta)
    return [[F(2 * y) / d, F(-1) / d], [F(1), F(0)]]


def check_H2plus(p=3, delta=3, c=-2, x0=1, y0=1, T=15):
    print(f"— Check 1: H+_II  (p={p}, delta={delta}, c={c}, start=({x0},{y0}))")
    orbit = [(x0, y0)]
    for _ in range(T):
        x, y = orbit[-1]
        orbit.append((y, y * y + c - delta * x))
    m = vp(delta, p)
    Mf = [[F(1), F(0)], [F(0), F(1)]]
    Mb = [[F(1), F(0)], [F(0), F(1)]]
    fwd, bwd = [], [None] * T
    for t in range(T):
        Mf = matmul(jac(*orbit[t], delta), Mf)
        fwd.append(snf_vals(Mf, p))
    for t in range(T - 1, -1, -1):
        Mb = matmul(Mb, jac_inv(*orbit[t], delta))
        bwd[t] = snf_vals(Mb, p)
    for t in range(T):
        assert fwd[t] == (0, (t + 1) * m), (t, fwd[t])
        assert bwd[t] == (-(T - t) * m, 0), (t, bwd[t])
    print(f"  forward exponents (0, t*m), backward (-(T-t)*m, 0) for t<=({T}): OK")
    print("  => forward never loses; smoother vacuous in H+_II.")


def check_H3(p=3, delta=1, alpha=F(1, 3), T=12):
    s = -vp(alpha, p)
    c = alpha + delta * alpha - alpha * alpha
    print(f"— Checks 2+3: H_III fixed point (p={p}, delta={delta}, "
          f"alpha={alpha}, c={c}, s={s})")
    J = jac(alpha, alpha, delta)
    Ji = jac_inv(alpha, alpha, delta)
    I2 = [[F(1), F(0)], [F(0), F(1)]]
    Fm, Bm = [I2], [I2]
    for _ in range(T):
        Fm.append(matmul(J, Fm[-1]))
        Bm.append(matmul(Bm[-1], Ji))
    for t in range(T + 1):
        assert snf_vals(Fm[t], p) == (-t * s, t * s), (t, snf_vals(Fm[t], p))
        L = intersect(Fm[t], Bm[T - t])
        lo = min(t, T - t) * s
        assert snf_vals(L, p) == (lo, T * s - lo), (t, snf_vals(L, p))
    print(f"  forward exponents (-t*s, t*s); smoothed (min(t,T-t)*s, ...) "
          f"for t<=({T}): OK")
    print("  => genuine loss forward; smoothed worst-direction precision is a "
          "bounded tent.")


if __name__ == "__main__":
    check_H2plus()
    check_H3()
    print("All review checks passed.")
